---

- name: Gather facts from network devices
  hosts: pa-fw01
  gather_facts: false
  connection: local

  tasks:
    - name: Include role to gather PAN-OS facts
      include_role:
        name: get_security_rule
