---

- name: Gather facts from network devices
  hosts: pa-fw01
  gather_facts: false
  connection: local

  tasks:
    - name: Gather Info for PANOS VM
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ fw01_provider }}"
        gathered_filter: "*"
        state: gathered
      register: result

    - name: Print gathered facts- PANOS VM
      debug:
        msg: "{{ result }}"
